# Generated by Django 4.1 on 2022-09-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatstrending', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date_published',
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
