# Generated by Django 4.1 on 2022-09-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatstrending', '0002_remove_article_date_published_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.URLField(default='google.com'),
        ),
        migrations.AlterField(
            model_name='article',
            name='descr',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
